/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NwA031WlFqd
 */
import { Avatar } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";

export function FeedPage() {
  return (
    <div className="grid gap-6 md:col-span-9">
      <div className="flex items-center gap-4">
        <Avatar className="h-16 w-16" />
        <h1 className="text-3xl font-bold">Feed</h1>
        <div className="ml-auto flex items-center gap-2">
          <Button className="h-8" size="sm" variant="outline">
            Create Post
          </Button>
        </div>
      </div>
      <div className="rounded-lg border border-gray-200">
        <div className="grid gap-2 border-b p-4">
          <div className="flex items-center gap-2">
            <Avatar className="h-8 w-8" />
            <div className="flex items-center gap-1">
              <h2 className="text-sm font-medium leading-none">Tracy Howard</h2>
              <h3 className="text-sm font-medium leading-none text-gray-500">
                @tracy123
              </h3>
            </div>
          </div>
          <div className="grid gap-2">
            <p className="text-base leading-[1.6]">
              Excited to announce the launch of our new app! It's been a long
              journey, but we're finally here. Big thanks to the team. #app
              #launch 🚀
            </p>
            <img
              alt="Post image"
              className="rounded-xl object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/200",
                objectFit: "cover",
              }}
              width="400"
            />
          </div>
          <div className="flex items-center gap-4">
            <Button size="sm" variant="outline">
              Comment
            </Button>
            <Button size="sm" variant="outline">
              Share
            </Button>
          </div>
        </div>
        <div className="grid gap-2 border-b p-4">
          <div className="flex items-center gap-2">
            <Avatar className="h-8 w-8" />
            <div className="flex items-center gap-1">
              <h2 className="text-sm font-medium leading-none">
                Kelly Thompson
              </h2>
              <h3 className="text-sm font-medium leading-none text-gray-500">
                @kellyt
              </h3>
            </div>
          </div>
          <div className="grid gap-2">
            <p className="text-base leading-[1.6]">
              Just finished reading the latest book by @author123. What a
              journey! Highly recommended for all the book lovers out there.
              📚❤️
            </p>
            <img
              alt="Post image"
              className="rounded-xl object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/200",
                objectFit: "cover",
              }}
              width="400"
            />
          </div>
          <div className="flex items-center gap-4">
            <Button size="sm" variant="outline">
              Comment
            </Button>
            <Button size="sm" variant="outline">
              Share
            </Button>
          </div>
        </div>
        <div className="grid gap-2 p-4">
          <div className="flex items-center gap-2">
            <Avatar className="h-8 w-8" />
            <div className="flex items-center gap-1">
              <h2 className="text-sm font-medium leading-none">Chris Parker</h2>
              <h3 className="text-sm font-medium leading-none text-gray-500">
                @thechris
              </h3>
            </div>
          </div>
          <div className="grid gap-2">
            <p className="text-base leading-[1.6]">
              Just wanted to share this amazing recipe I tried last night.
              It&apos;s a delicious spaghetti aglio e olio. 😋🍝
            </p>
            <img
              alt="Post image"
              className="rounded-xl object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/200",
                objectFit: "cover",
              }}
              width="400"
            />
          </div>
          <div className="flex items-center gap-4">
            <Button size="sm" variant="outline">
              Comment
            </Button>
            <Button size="sm" variant="outline">
              Share
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

interface PostCardProps {
  name: string;
  username: string;
  postText: string;
  imgSrc: string;
}

const PostCard: React.FC<PostCardProps> = ({
  name,
  username,
  postText,
  imgSrc,
}) => {
  return (
    <div className="grid gap-2 border-b p-4">
      <div className="flex items-center gap-2">
        <Avatar className="h-8 w-8" />
        <div className="flex items-center gap-1">
          <h2 className="text-sm font-medium leading-none">{name}</h2>
          <h3 className="text-sm font-medium leading-none text-gray-500">
            @{username}
          </h3>
        </div>
      </div>
      <div className="grid gap-2">
        <p className="text-base leading-[1.6]">{postText}</p>
        <img
          alt="Post image"
          className="rounded-xl object-cover"
          height="200"
          src={imgSrc}
          style={{
            aspectRatio: "400/200",
            objectFit: "cover",
          }}
          width="400"
        />
      </div>
      <div className="flex items-center gap-4">
        <Button size="sm" variant="outline">
          Comment
        </Button>
        <Button size="sm" variant="outline">
          Share
        </Button>
      </div>
    </div>
  );
};

export default PostCard;
