/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NwA031WlFqd
 */
import { Avatar } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";

export function FeedPage() {
  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <h1 className="text-3xl font-bold">Feed</h1>
        <div className="ml-auto flex items-center gap-2">
          <Button size="lg" variant="outline">
            Create Post
          </Button>
        </div>
      </div>
      <div className="rounded-lg border border-gray-200">
        <PostCard
          name="Tracy Howard"
          username="tracy123"
          postText="Just finished reading the latest book by @author123. What a journey! Highly recommended for all the book lovers out there. 📚❤️"
          imgSrc="/placeholder.svg"
        />
        <PostCard
          name="Kelly Thompson"
          username="kellyt"
          postText="Just finished reading the latest book by @author123. What a journey! Highly recommended for all the book lovers out there. 📚❤️"
          imgSrc="/placeholder.svg"
        />
        <PostCard
          name="Chris Parker"
          username="thechris"
          postText="Just wanted to share this amazing recipe I tried last night. It's a delicious spaghetti aglio e olio. 😋🍝"
          imgSrc="/placeholder.svg"
        />
      </div>
    </div>
  );
}

interface PostCardProps {
  name: string;
  username: string;
  postText: string;
  imgSrc: string;
}

const PostCard: React.FC<PostCardProps> = ({
  name,
  username,
  postText,
  imgSrc,
}) => {
  return (
    <div className="grid gap-2 border-b p-4">
      <div className="flex items-center gap-2">
        <Avatar />
        <div className="flex items-center gap-1">
          <h2 className="text-sm font-medium leading-none">{name}</h2>
          <h3 className="text-sm font-medium leading-none text-gray-500">
            @{username}
          </h3>
        </div>
      </div>
      <div className="grid items-center">
        <p className="text-base leading-[1.6]">{postText}</p>
        <img
          alt="Post image"
          className="mx-auto my-4 rounded-xl object-cover"
          height="200"
          src={imgSrc}
          style={{
            aspectRatio: "400/200",
            objectFit: "cover",
          }}
          width="400"
        />
      </div>
      <div className="mx-auto flex items-center gap-4">
        <Button size="sm" variant="outline">
          Comment
          <TextIcon className="ml-1 h-4 w-4" />
        </Button>
        <Button size="sm" variant="outline">
          Share
          <ShareIcon className="ml-1 h-4 w-4" />
        </Button>
      </div>
    </div>
  );
};

export default PostCard;

type IconProps = React.ComponentProps<"svg">;

function TextIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 6.1H3" />
      <path d="M21 12.1H3" />
      <path d="M15.1 18H3" />
    </svg>
  );
}

function ShareIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <polyline points="16 6 12 2 8 6" />
      <line x1="12" x2="12" y1="2" y2="15" />
    </svg>
  );
}
