/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NwA031WlFqd
 */
import { PostCard } from "@/components/post-card";
import { Button } from "@/components/ui/button";

function FeedPage() {
  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <h1 className="text-3xl font-bold">Feed</h1>
        <div className="ml-auto flex items-center gap-2">
          <Button size="lg" variant="outline">
            Nova Postagem
          </Button>
        </div>
      </div>
      <div className="rounded-lg border border-gray-200">
        {posts.map((post) => (
          <PostCard
            key={post.id}
            name={post.name}
            username={post.username}
            postText={post.postText}
            imgSrc={post.imgSrc}
          />
        ))}
      </div>
    </div>
  );
}

const posts = [
  {
    id: "1",
    name: "Tracy Howard",
    username: "tracy123",
    postText:
      "Just finished reading the latest book by @author123. What a journey! Highly recommended for all the book lovers out there. 📚❤️",
    imgSrc: "/placeholder.svg",
  },
  {
    id: "2",
    name: "Kelly Thompson",
    username: "kellyt",
    postText:
      "Just finished reading the latest book by @author123. What a journey! Highly recommended for all the book lovers out there. 📚❤️",
    imgSrc: "/placeholder.svg",
  },
  {
    id: "3",
    name: "Chris Parker",
    username: "thechris",
    postText:
      "Just wanted to share this amazing recipe I tried last night. It's a delicious spaghetti aglio e olio. 😋🍝",
    imgSrc: "/placeholder.svg",
  },
];

export default FeedPage;
