/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NwA031WlFqd
 */
import { BaseHeader } from "@/components/base-header";
import { PostCard } from "@/components/post-card";
import { Button } from "@/components/ui/button";

function FeedPage() {
  return (
    <>
      <BaseHeader title="Feed">
        <Button size="lg">Nova Postagem</Button>
      </BaseHeader>

      <div className="rounded-lg border border-gray-200">
        {posts.map((post) => (
          <PostCard
            key={post.id}
            id={post.id}
            name={post.name}
            username={post.username}
            postText={post.postText}
            imgSrc={post.imgSrc}
          />
        ))}
      </div>
    </>
  );
}

const posts = [
  {
    id: "1",
    name: "Tracy Howard",
    username: "tracy123",
    postText:
      "Just finished reading the latest book by @author123. What a journey! Highly recommended for all the book lovers out there. 📚❤️",
    imgSrc: "/placeholder.svg",
  },
  {
    id: "2",
    name: "Kelly Thompson",
    username: "kellyt",
    postText:
      "Just finished reading the latest book by @author123. What a journey! Highly recommended for all the book lovers out there. 📚❤️",
    imgSrc: "/placeholder.svg",
  },
  {
    id: "3",
    name: "Chris Parker",
    username: "thechris",
    postText:
      "Just wanted to share this amazing recipe I tried last night. It's a delicious spaghetti aglio e olio. 😋🍝",
    imgSrc: "/placeholder.svg",
  },
];

export default FeedPage;
